-- Card Generator Database Schema
-- SQLite 3
-- Auto-generated by DatabaseManager.initialise_schema()

CREATE TABLE IF NOT EXISTS templates (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    template_name TEXT    NOT NULL,
    front_image   TEXT,
    back_image    TEXT,
    canvas_width  REAL    NOT NULL DEFAULT 85.6,
    canvas_height REAL    NOT NULL DEFAULT 54.0,
    grid_size     INTEGER NOT NULL DEFAULT 10,
    snap_to_grid  INTEGER NOT NULL DEFAULT 1,
    zoom_level    REAL    NOT NULL DEFAULT 100.0,
    created_at    TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at    TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS template_fields (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    template_id      INTEGER NOT NULL,
    object_type      TEXT    NOT NULL DEFAULT 'text_field',
    field_name       TEXT    NOT NULL,
    display_name     TEXT    NOT NULL DEFAULT '',
    field_type       TEXT    NOT NULL DEFAULT 'text',
    x                REAL    NOT NULL DEFAULT 0.0,
    y                REAL    NOT NULL DEFAULT 0.0,
    width            REAL    NOT NULL DEFAULT 100.0,
    height           REAL    NOT NULL DEFAULT 20.0,
    font_family      TEXT    NOT NULL DEFAULT 'Arial',
    font_size        INTEGER NOT NULL DEFAULT 12,
    font_color       TEXT    NOT NULL DEFAULT '#000000',
    background_color TEXT    NOT NULL DEFAULT '#FFFFFF',
    bold             INTEGER NOT NULL DEFAULT 0,
    italic           INTEGER NOT NULL DEFAULT 0,
    underline        INTEGER NOT NULL DEFAULT 0,
    alignment        TEXT    NOT NULL DEFAULT 'left',
    rotation         INTEGER NOT NULL DEFAULT 0,
    opacity          REAL    NOT NULL DEFAULT 1.0,
    visible          INTEGER NOT NULL DEFAULT 1,
    locked           INTEGER NOT NULL DEFAULT 0,
    required         INTEGER NOT NULL DEFAULT 0,
    default_value    TEXT    NOT NULL DEFAULT '',
    z_order          INTEGER NOT NULL DEFAULT 0,
    page_side        TEXT    NOT NULL DEFAULT 'front',
    created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (template_id) REFERENCES templates(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dependents (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    card_id       INTEGER,
    name          TEXT    NOT NULL,
    relation      TEXT    NOT NULL DEFAULT '',
    date_of_birth TEXT    NOT NULL DEFAULT '',
    cnic          TEXT    NOT NULL DEFAULT '',
    created_at    TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cards (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    template_id       INTEGER NOT NULL,
    photo_path        TEXT,
    employee_name     TEXT,
    designation       TEXT,
    employee_category TEXT,
    blood_group       TEXT,
    location          TEXT,
    dependence        TEXT,
    front_output      TEXT,
    back_output       TEXT,
    combined_pdf      TEXT,
    created_at        TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at        TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (template_id) REFERENCES templates(id) ON DELETE SET NULL
);
